create table tb_conta (id int8 generated by default as identity, cpf varchar(255), nome varchar(255), numero_conta int4, saldo float8, primary key (id));
create table tb_deposito (id int8 generated by default as identity, valor float8, conta_id int8, primary key (id));
create table tb_transferencia (id int8 generated by default as identity, valor float8, conta_destino_id int8, conta_origem_id int8, primary key (id));
alter table if exists tb_deposito add constraint FKp79rbahkkjr4fidl2falisarm foreign key (conta_id) references tb_conta;
alter table if exists tb_transferencia add constraint FKfv09gvc2w62lyuvg6rjma5yn0 foreign key (conta_destino_id) references tb_conta;
alter table if exists tb_transferencia add constraint FKsyh9uqqixdusq53nvd4muqylv foreign key (conta_origem_id) references tb_conta;
